const x = 10;

try {
  x = 20;
} catch (err) {
  console.log(`Erro ${err}`);
}
